# stage3_per_subclass_crops.py
"""
Stage-3: Per-subclass fine-grained LU_CODE classifiers

- For each subclass produced by Stage-2 (orchards, plantation, field, other_econ),
  train a classifier that maps economic pixels in that subclass to the LU_CODE
  (fine-grained crop label) among LU codes assigned to that subclass.

Assumptions / expected inputs (same dir as your other scripts):
 - NPZ with features + true LU_CODE: ./aligned_features/svm_new_features_labels.npz
    contains arrays "X" (float32) and "y" (int32)
 - Stage-1 predictions: stage1_pred_new_features.npy (or will be generated by loading stage1 model)
 - Stage-2 subclass predictions/model: stage2_subclass_pred.npy or stage2_subclass_model.joblib
Outputs (per subclass):
 - stage3_{subclass}_model.joblib
 - stage3_{subclass}_report.csv
 - stage3_{subclass}_test_prob.npy
 - stage3_{subclass}_test_pred.npy
 - stage3_{subclass}_meta.json
Top-level:
 - stage3_meta.json
"""
import os
import json
import numpy as np
import joblib
import pandas as pd
from collections import Counter
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.kernel_approximation import Nystroem
from sklearn.multiclass import OneVsRestClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, confusion_matrix, f1_score

# -----------------------
# Config - edit if needed
# -----------------------
NPZ = "./aligned_features/svm_new_features_labels.npz"

# Stage-1 outputs (from your Stage-1 script)
STAGE1_PRED = "stage1_pred_new_superclass.npy"
STAGE1_MODEL = "stage1_svm_pred_chunk_new_superclass.joblib"
STAGE1_CHUNK = 2_000_000

# Stage-2 outputs (subclass)
STAGE2_PRED = "stage2_subclass_pred.npy"
STAGE2_MODEL = "stage2_subclass_model.joblib"
STAGE2_CHUNK = 2_000_000

RANDOM_STATE = 42

# your economic LU codes (same as Stage-2)
economic_crops = {2101,2204,2205,2302,2303,2403,2404,2405,2407,2413,2416,2419,2420}

# SUBCLASS grouping: ensure coconut is 2405 in plantation
orchards_codes = {2403, 2404, 2407, 2420, 2416, 2419}
plantation_codes = {2302, 2303, 2405}   # Para rubber(2302), Oil palm(2303), Coconut(2405)
field_codes = {2101, 2204, 2205}        # Active paddy(2101), Cassava(2204), Pineapple(2205)
# fallback: economic_crops not in any of the above -> other_econ

SUBCLASS_LABELS = {"orchards": 1, "plantation": 2, "field": 3, "other_econ": 4}
SUBCLASS_TO_CODES = {
    1: sorted(list(orchards_codes)),
    2: sorted(list(plantation_codes)),
    3: sorted(list(field_codes)),
    4: sorted([c for c in economic_crops if (c not in orchards_codes and c not in plantation_codes and c not in field_codes)])
}

# Stage-3 sampling / training config (per-LU)
MIN_PIXELS_PER_LU = 100       # drop LU_CODEs with fewer than this pixels
PER_LU_CAP = 24000            # cap per LU before split
TARGET_PER_LU = 6000          # target train size per LU (upsample small LU to this)
UPSAMPLE_SMALL = True
CONDITIONAL_UPSAMPLE = True
MIN_UPSAMPLE_TRIGGER = 0.67
TUNE_THRESHOLDS = False
THRESH_GRID = np.linspace(0.2, 0.95, 40)

# search / pipelines (same style as earlier stages)
NYST_COMPONENTS = [400, 600]
NYST_GAMMA = [0.5, 1.0]
SVC_C = [0.1, 1.0, 10.0]
N_ITER_SEARCH = 8
N_JOBS = 4

# Outputs naming pattern
OUT_MODEL_TPL = "stage3_{grp}_model.joblib"
OUT_REPORT_TPL = "stage3_{grp}_report.csv"
OUT_TEST_PROB_TPL = "stage3_{grp}_test_prob.npy"
OUT_TEST_PRED_TPL = "stage3_{grp}_test_pred.npy"
OUT_META_TPL = "stage3_{grp}_meta.json"

OUT_TOP_META = "stage3_meta.json"

# -----------------------
# Helpers (stage-1 & stage-2 preds)
# -----------------------
def ensure_stage1_pred(npz_path, pred_npy=STAGE1_PRED, model_path=STAGE1_MODEL, chunk_size=STAGE1_CHUNK):
    if os.path.exists(pred_npy):
        print("Found Stage-1 predictions:", pred_npy)
        return np.load(pred_npy)
    if not os.path.exists(model_path):
        raise FileNotFoundError("Neither stage1_pred nor stage1 model found. Run Stage-1 first.")
    print("Generating Stage-1 predictions using model:", model_path)
    model = joblib.load(model_path)
    data = np.load(npz_path, allow_pickle=True)
    X_all = data["X"].astype(np.float32)
    n = X_all.shape[0]
    preds = np.zeros(n, dtype=np.uint8)
    for s in range(0, n, chunk_size):
        e = min(n, s+chunk_size)
        preds[s:e] = model.predict(X_all[s:e]).astype(np.uint8)
        print(f"  Stage-1 predict chunk {s}:{e}")
    np.save(pred_npy, preds)
    print("Saved Stage-1 predictions to", pred_npy)
    return preds

def ensure_stage2_pred(npz_path, stage1_pred_array, pred_npy=STAGE2_PRED, model_path=STAGE2_MODEL, chunk_size=STAGE2_CHUNK):
    """
    Stage-2 subclass predictions aligned with full dataset indices:
    - output is an int32 array of length n (same shape as dataset), where
      positions not predicted econ by Stage-1 are set to 0, and econ pixels
      have subclass labels 1..4.
    """
    if os.path.exists(pred_npy):
        print("Found Stage-2 subclass predictions:", pred_npy)
        return np.load(pred_npy)
    # if model not present, cannot generate - user must run Stage-2 first
    if not os.path.exists(model_path):
        raise FileNotFoundError("Neither stage2_subclass_pred.npy nor stage2_subclass_model.joblib found. Run Stage-2 first.")
    print("Generating Stage-2 subclass predictions (full-aligned) using model:", model_path)
    model = joblib.load(model_path)
    data = np.load(npz_path, allow_pickle=True)
    X_all = data["X"].astype(np.float32)
    n = X_all.shape[0]
    preds_full = np.zeros(n, dtype=np.int32)  # 0 = non-econ (or unknown)
    # only predict where stage1_pred == 1
    mask = (stage1_pred_array == 1)
    idxs = np.flatnonzero(mask)
    print("Will predict subclass for", idxs.size, "econ pixels.")
    # predict in chunks over idxs to save memory
    for s in range(0, idxs.size, chunk_size):
        e = min(idxs.size, s+chunk_size)
        sel = idxs[s:e]
        Xc = X_all[sel]
        preds_full[sel] = model.predict(Xc).astype(np.int32)
        print(f"  Stage-2 predict chunk {s}:{e} -> indices {sel[0]}:{sel[-1]+1}")
    np.save(pred_npy, preds_full)
    print("Saved Stage-2 subclass predictions to", pred_npy)
    return preds_full

# -----------------------
# Stage-3 helpers: per-LU sampling / upsampling / report
# -----------------------
def load_Xy(npz_path):
    d = np.load(npz_path, allow_pickle=True)
    return d["X"].astype(np.float32), d["y"].astype(np.int32)

def cap_per_lu(X, y, cap=PER_LU_CAP):
    rng = np.random.default_rng(RANDOM_STATE)
    partsX, partsy = [], []
    for c in np.unique(y):
        idxs = np.flatnonzero(y == c)
        if len(idxs) > cap:
            chosen = rng.choice(idxs, size=cap, replace=False)
        else:
            chosen = idxs
        partsX.append(X[chosen]); partsy.append(y[chosen])
        print(f"LU {int(c)}: available={len(idxs)}, kept={len(chosen)}")
    Xc = np.vstack(partsX); yc = np.hstack(partsy)
    p = rng.permutation(Xc.shape[0])
    return Xc[p], yc[p]

def sample_per_lu_train_only(X_train, y_train, target_per_lu=TARGET_PER_LU, upsample=UPSAMPLE_SMALL,
                             conditional=CONDITIONAL_UPSAMPLE, min_trigger=MIN_UPSAMPLE_TRIGGER):
    rng = np.random.default_rng(RANDOM_STATE)
    lus = np.unique(y_train)
    partsX, partsy = [], []
    for c in lus:
        idxs = np.flatnonzero(y_train == c)
        n = idxs.size
        tgt = int(target_per_lu)
        effective_target = tgt
        if conditional:
            if n >= tgt:
                effective_target = n
            elif n >= min_trigger * tgt:
                effective_target = tgt
            else:
                effective_target = tgt
        else:
            effective_target = tgt
        if n >= effective_target:
            chosen = rng.choice(idxs, size=effective_target, replace=False)
        else:
            chosen = rng.choice(idxs, size=effective_target, replace=True) if upsample else idxs
        partsX.append(X_train[chosen]); partsy.append(y_train[chosen])
        print(f"LU {int(c)}: train n={n} -> final={len(chosen)} target_policy={effective_target}")
    Xb = np.vstack(partsX); yb = np.hstack(partsy)
    perm = rng.permutation(Xb.shape[0])
    return Xb[perm], yb[perm]

def save_report_with_traininfo(report_dict, train_unique_counts, train_final_counts, test_counts, out_csv):
    df = pd.DataFrame(report_dict).transpose()
    train_unique = []
    train_final = []
    test_supp = []
    for idx in df.index:
        try:
            cls = int(idx)   # LU_CODE numeric string
            train_unique.append(train_unique_counts.get(cls, 0))
            train_final.append(train_final_counts.get(cls, 0))
            test_supp.append(test_counts.get(cls, 0))
        except:
            train_unique.append("")
            train_final.append("")
            test_supp.append("")
    df["train_unique_support"] = train_unique
    df["train_final_support"] = train_final
    df["test_support"] = test_supp
    df.to_csv(out_csv, index=True, encoding="utf-8-sig")
    print("Saved report:", out_csv)

# -----------------------
# Main: loop over subclasses and train per-LU classifiers
# -----------------------
if __name__ == "__main__":
    print("=== Stage-3: per-subclass LU_CODE classifiers ===")

    # ensure stage-1 preds (full-aligned array)
    stage1_pred = ensure_stage1_pred(NPZ, STAGE1_PRED, STAGE1_MODEL, chunk_size=STAGE1_CHUNK)

    # ensure stage-2 subclass preds (full-aligned array); will raise if stage2 model is missing
    stage2_pred = ensure_stage2_pred(NPZ, stage1_pred, pred_npy=STAGE2_PRED, model_path=STAGE2_MODEL, chunk_size=STAGE2_CHUNK)

    X_all, y_all = load_Xy(NPZ)
    n_all = X_all.shape[0]
    print("Loaded dataset:", X_all.shape, y_all.shape)

    # work only on econ pixels (stage1_pred == 1)
    econ_mask = (stage1_pred == 1)
    econ_idxs = np.flatnonzero(econ_mask)
    print("Total econ pixels (stage1==1):", econ_idxs.size)

    top_meta = {
        "stage": 3,
        "trained_subclasses": {},
        "config": {
            "MIN_PIXELS_PER_LU": MIN_PIXELS_PER_LU,
            "PER_LU_CAP": PER_LU_CAP,
            "TARGET_PER_LU": TARGET_PER_LU,
            "UPSAMPLE_SMALL": UPSAMPLE_SMALL,
            "CONDITIONAL_UPSAMPLE": CONDITIONAL_UPSAMPLE,
            "MIN_UPSAMPLE_TRIGGER": MIN_UPSAMPLE_TRIGGER,
            "NYST_COMPONENTS": NYST_COMPONENTS,
            "NYST_GAMMA": NYST_GAMMA,
            "SVC_C": SVC_C,
            "N_ITER_SEARCH": N_ITER_SEARCH
        }
    }

    # For each subclass label we will build a per-LU classifier
    for subclass_label, lu_list in SUBCLASS_TO_CODES.items():
        # friendly name
        name = [k for k,v in SUBCLASS_LABELS.items() if v == subclass_label]
        name = name[0] if name else f"subclass_{subclass_label}"
        print(f"\n--- Processing subclass {name} (label={subclass_label}) with LU codes: {lu_list} ---")

        if len(lu_list) == 0:
            print(f"No LU codes assigned to subclass {name}; skipping.")
            continue

        # select indices where (stage1_pred==1) AND (stage2_pred == subclass_label) AND true LU_CODE in lu_list
        mask = (stage1_pred == 1) & (stage2_pred == subclass_label) & np.isin(y_all, lu_list)
        idxs = np.flatnonzero(mask)
        print(f"Pixels in this subclass & LU_list: {idxs.size}")

        if idxs.size == 0:
            print("No samples for this subclass (after filtering). Skipping.")
            continue

        X_sub = X_all[idxs]
        y_sub = y_all[idxs]  # true LU_CODEs (fine-grained labels)

        # drop LU codes with too few pixels
        uniques, counts = np.unique(y_sub, return_counts=True)
        keep_lu = uniques[counts >= MIN_PIXELS_PER_LU]
        if keep_lu.size == 0:
            print(f"No LU codes in subclass {name} pass MIN_PIXELS_PER_LU={MIN_PIXELS_PER_LU}. Skipping.")
            continue
        mask_keep = np.isin(y_sub, keep_lu)
        X_keep = X_sub[mask_keep]; y_keep = y_sub[mask_keep]
        print(f"After dropping tiny LU codes: {X_keep.shape[0]} samples, LU_count={len(keep_lu)}")

        # cap per-LU
        Xc, yc = cap_per_lu(X_keep, y_keep, cap=PER_LU_CAP)

        # split train/val/test
        X_tr, X_rest, y_tr, y_rest = train_test_split(Xc, yc, test_size=0.3, stratify=yc, random_state=RANDOM_STATE)
        X_val, X_te, y_val, y_te = train_test_split(X_rest, y_rest, test_size=0.5, stratify=y_rest, random_state=RANDOM_STATE)
        print("Split sizes (train,val,test):", X_tr.shape[0], X_val.shape[0], X_te.shape[0])

        train_unique_counts = dict(Counter(y_tr))

        # conditional upsample to TARGET_PER_LU for train-only
        X_tr_bal, y_tr_bal = sample_per_lu_train_only(
            X_tr, y_tr, target_per_lu=TARGET_PER_LU,
            upsample=UPSAMPLE_SMALL, conditional=CONDITIONAL_UPSAMPLE, min_trigger=MIN_UPSAMPLE_TRIGGER
        )
        train_final_counts = dict(Counter(y_tr_bal))
        print("Train dist (final balanced):", train_final_counts)
        too_small = [c for c,n in train_final_counts.items() if n < 3]
        if too_small:
            print("Some LU codes too small for 3-fold CV, skipping this subclass:", too_small)
            continue

        # build pipeline (same pattern)
        steps = [('scaler', StandardScaler()), ('nyst', Nystroem(kernel='rbf', random_state=RANDOM_STATE)),
                 ('svc', LinearSVC(class_weight='balanced', max_iter=20000, random_state=RANDOM_STATE))]
        pipe = Pipeline(steps)
        ovr = OneVsRestClassifier(pipe)
        calibrated = CalibratedClassifierCV(estimator=ovr, cv=3, method='sigmoid')

        param_dist = {
            'estimator__estimator__nyst__n_components': NYST_COMPONENTS,
            'estimator__estimator__nyst__gamma': NYST_GAMMA,
            'estimator__estimator__svc__C': SVC_C
        }

        print("Starting RandomizedSearchCV for subclass", name)
        rsearch = RandomizedSearchCV(calibrated, param_distributions=param_dist, n_iter=N_ITER_SEARCH, cv=3,
                                     random_state=RANDOM_STATE, n_jobs=N_JOBS, verbose=2)
        rsearch.fit(X_tr_bal, y_tr_bal)
        print("Best params:", rsearch.best_params_)

        best_clf = rsearch.best_estimator_
        lu_classes = best_clf.classes_
        print("LU classes (model):", lu_classes)

        # Optional threshold tuning (per LU) - usually not necessary for multiclass LU classification
        thresholds = {int(c): None for c in lu_classes}
        if TUNE_THRESHOLDS:
            val_probs = best_clf.predict_proba(X_val)
            base_val = lu_classes[np.argmax(val_probs, axis=1)]
            idx_map = {c:i for i,c in enumerate(lu_classes)}
            for cls in lu_classes:
                best_f1=-1.0; best_t=None
                col = idx_map[cls]
                for t in THRESH_GRID:
                    labels = base_val.copy()
                    labels[val_probs[:, col] > t] = cls
                    f1 = f1_score(y_val, labels, labels=[cls], average='macro')
                    if f1 > best_f1:
                        best_f1=f1; best_t=t
                thresholds[int(cls)] = float(best_t) if best_t is not None else None
            print("Thresholds (per-LU):", thresholds)
        else:
            print("Threshold tuning disabled for Stage-3 (TUNE_THRESHOLDS=False)")

        # test evaluation
        test_probs = best_clf.predict_proba(X_te)
        np.save(OUT_TEST_PROB_TPL.format(grp=name), test_probs.astype(np.float32))
        if TUNE_THRESHOLDS and any(v is not None for v in thresholds.values()):
            base_test = lu_classes[np.argmax(test_probs, axis=1)]
            idx_map = {c:i for i,c in enumerate(lu_classes)}
            test_pred = base_test.copy()
            for cls, t in thresholds.items():
                if t is None: continue
                col = idx_map[cls]
                mask = test_probs[:, col] > t
                test_pred[mask] = cls
        else:
            test_pred = lu_classes[np.argmax(test_probs, axis=1)]
        np.save(OUT_TEST_PRED_TPL.format(grp=name), test_pred.astype(np.int32))
        print("Saved test probs/preds for", name)

        report = classification_report(y_te, test_pred, output_dict=True)
        test_counts = dict(Counter(y_te))
        save_report_with_traininfo(report, train_unique_counts, train_final_counts, test_counts, OUT_REPORT_TPL.format(grp=name))

        print("Confusion matrix for", name)
        print(confusion_matrix(y_te, test_pred))

        # save model & meta
        joblib.dump(best_clf, OUT_MODEL_TPL.format(grp=name))
        meta = {
            "subclass": name,
            "subclass_label": int(subclass_label),
            "lu_codes_trained": [int(x) for x in lu_classes],
            "counts": {
                "train_unique": {int(k): int(v) for k,v in train_unique_counts.items()},
                "train_final": {int(k): int(v) for k,v in train_final_counts.items()},
                "test": {int(k): int(v) for k,v in test_counts.items()}
            },
            "best_params": rsearch.best_params_,
            "thresholds": thresholds
        }
        with open(OUT_META_TPL.format(grp=name), 'w') as fm:
            json.dump(meta, fm, indent=2)
        print("Saved Stage-3 model & meta for", name)

        # record in top meta
        top_meta["trained_subclasses"][name] = {
            "label": int(subclass_label),
            "lu_codes_trained": [int(x) for x in lu_classes],
            "model": OUT_MODEL_TPL.format(grp=name),
            "report": OUT_REPORT_TPL.format(grp=name),
            "test_prob": OUT_TEST_PROB_TPL.format(grp=name),
            "test_pred": OUT_TEST_PRED_TPL.format(grp=name),
            "meta": OUT_META_TPL.format(grp=name)
        }

    # Save top-level meta
    with open(OUT_TOP_META, 'w') as ftop:
        json.dump(top_meta, ftop, indent=2)
    print("Saved top-level Stage-3 meta:", OUT_TOP_META)
    print("Stage-3 complete.")
